language: node_js
git:
  depth: 10
notifications:
  email: false
node_js:
  - "12.18.1"
matrix:
  include:
    - os: linux
      env: TARGET_ARCH=arm
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - npm install
  - npm test
