#
# This is a sample docker-compose file, normally you will be using FROM to inherit oak
# If you run this project, it will use `default/index.js` by default
#
version: '2'
services:
  oak:
    build: .
    container_name: oak
    image: oaklabs/oak:4.3.2
    network_mode: host
    devices:
      # our video card device, may vary per operating system
      - /dev/dri:/dev/dri
      # For NVIDIA devices
      # - /dev/nvidia0:/dev/nvidia0
      # - /dev/nvidiactl:/dev/nvidiactl
    volumes:
      # share memory
      - /dev/shm:/dev/shm
      # mount our X server socket
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - ./build:/build
