---
version: '2'
services:
  multiplewindows:
    build: .
    container_name: multiple-windows
    image: oaklabs/multiple-windows:latest
    network_mode: host
    devices:
      # remove if you dont need to share your graphics card explicitely
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
